version: '3.3'
services:
  bot:
    container_name: 'bot'
    build: './'

    depends_on:
      - 'mongo'

  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - '27017:27017'